#if 0
#elif defined(__x86_64__) && __x86_64__
// Generated by Apple Swift version 5.2.4 (swiftlang-1103.0.32.9 clang-1103.0.32.53)
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wgcc-compat"

#if !defined(__has_include)
# define __has_include(x) 0
#endif
#if !defined(__has_attribute)
# define __has_attribute(x) 0
#endif
#if !defined(__has_feature)
# define __has_feature(x) 0
#endif
#if !defined(__has_warning)
# define __has_warning(x) 0
#endif

#if __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#include <Foundation/Foundation.h>
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus)
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...)
# endif
#endif

#if __has_attribute(objc_runtime_name)
# define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
#else
# define SWIFT_RUNTIME_NAME(X)
#endif
#if __has_attribute(swift_name)
# define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
#else
# define SWIFT_COMPILE_NAME(X)
#endif
#if __has_attribute(objc_method_family)
# define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
#else
# define SWIFT_METHOD_FAMILY(X)
#endif
#if __has_attribute(noescape)
# define SWIFT_NOESCAPE __attribute__((noescape))
#else
# define SWIFT_NOESCAPE
#endif
#if __has_attribute(ns_consumed)
# define SWIFT_RELEASES_ARGUMENT __attribute__((ns_consumed))
#else
# define SWIFT_RELEASES_ARGUMENT
#endif
#if __has_attribute(warn_unused_result)
# define SWIFT_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
#else
# define SWIFT_WARN_UNUSED_RESULT
#endif
#if __has_attribute(noreturn)
# define SWIFT_NORETURN __attribute__((noreturn))
#else
# define SWIFT_NORETURN
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA
#endif
#if !defined(SWIFT_CLASS)
# if __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif
#if !defined(SWIFT_RESILIENT_CLASS)
# if __has_attribute(objc_class_stub)
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME) __attribute__((objc_class_stub))
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_class_stub)) SWIFT_CLASS_NAMED(SWIFT_NAME)
# else
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME)
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) SWIFT_CLASS_NAMED(SWIFT_NAME)
# endif
#endif

#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif

#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif

#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER
# endif
#endif
#if !defined(SWIFT_ENUM_ATTR)
# if defined(__has_attribute) && __has_attribute(enum_extensibility)
#  define SWIFT_ENUM_ATTR(_extensibility) __attribute__((enum_extensibility(_extensibility)))
# else
#  define SWIFT_ENUM_ATTR(_extensibility)
# endif
#endif
#if !defined(SWIFT_ENUM)
# define SWIFT_ENUM(_type, _name, _extensibility) enum _name : _type _name; enum SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# if __has_feature(generalized_swift_name)
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# else
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if !defined(SWIFT_UNAVAILABLE_MSG)
# define SWIFT_UNAVAILABLE_MSG(msg) __attribute__((unavailable(msg)))
#endif
#if !defined(SWIFT_AVAILABILITY)
# define SWIFT_AVAILABILITY(plat, ...) __attribute__((availability(plat, __VA_ARGS__)))
#endif
#if !defined(SWIFT_WEAK_IMPORT)
# define SWIFT_WEAK_IMPORT __attribute__((weak_import))
#endif
#if !defined(SWIFT_DEPRECATED)
# define SWIFT_DEPRECATED __attribute__((deprecated))
#endif
#if !defined(SWIFT_DEPRECATED_MSG)
# define SWIFT_DEPRECATED_MSG(...) __attribute__((deprecated(__VA_ARGS__)))
#endif
#if __has_feature(attribute_diagnose_if_objc)
# define SWIFT_DEPRECATED_OBJC(Msg) __attribute__((diagnose_if(1, Msg, "warning")))
#else
# define SWIFT_DEPRECATED_OBJC(Msg) SWIFT_DEPRECATED_MSG(Msg)
#endif
#if !defined(IBSegueAction)
# define IBSegueAction
#endif
#if __has_feature(modules)
#if __has_warning("-Watimport-in-framework-header")
#pragma clang diagnostic ignored "-Watimport-in-framework-header"
#endif
@import Foundation;
@import ObjectiveC;
#endif

#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="TrustVisionAPI",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif


SWIFT_PROTOCOL("_TtP14TrustVisionAPI18DeviceInfoProtocol_")
@protocol DeviceInfoProtocol
- (NSString * _Nonnull)getPlatform SWIFT_WARN_UNUSED_RESULT;
- (NSString * _Nonnull)getOSVersion SWIFT_WARN_UNUSED_RESULT;
- (NSString * _Nonnull)getSDKVersion SWIFT_WARN_UNUSED_RESULT;
- (NSString * _Nonnull)getDeviceModel SWIFT_WARN_UNUSED_RESULT;
@end

@class TVApiError;
@class TVClientSettingsResponse;
@class TVRequestVideoFrame;
@class TVCardInfoRequest;
@class TVCardInfoResponse;
@class TVCompareFacesResponse;
@class TVVerifyLivenessResponse;
@class TVVerifyIdCardSanityResponse;
@class TVVerifyPortraitSanityResponse;
@class TVRequestImage;
@class TVCardInfoSyncRequest;
@class TVRequestGestureImage;
@class TVRequestVideo;
@class TVCardTamperingRequest;
@class TVDetectIdCardTamperingResponse;
@class UIImage;
@class TVLogRequest;

SWIFT_CLASS("_TtC14TrustVisionAPI11TVAPIClient")
@interface TVAPIClient : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (void)setupWithBaseUrl:(NSString * _Nullable)baseUrl deviceInfo:(id <DeviceInfoProtocol> _Nonnull)deviceInfo getAuthorization:(void (^ _Nonnull)(NSString * _Nullable, NSString * _Nullable, SWIFT_NOESCAPE void (^ _Nonnull)(NSString * _Nullable, NSString * _Nullable, NSString * _Nullable)))getAuthorization errorHandler:(void (^ _Nullable)(NSArray<TVApiError *> * _Nonnull))errorHandler;
- (NSString * _Nonnull)getClientSettingsWithCompletion:(void (^ _Nonnull)(NSArray<TVApiError *> * _Nonnull, TVClientSettingsResponse * _Nullable))completion SWIFT_WARN_UNUSED_RESULT;
- (NSString * _Nonnull)uploadVideoWithVideoData:(NSData * _Nullable)videoData frames:(NSArray<TVRequestVideoFrame *> * _Nullable)frames label:(NSString * _Nullable)label metadata:(NSDictionary<NSString *, id> * _Nullable)metadata completion:(void (^ _Nonnull)(NSArray<TVApiError *> * _Nonnull, NSString * _Nullable))completion SWIFT_WARN_UNUSED_RESULT;
- (NSString * _Nonnull)uploadImageWithImageData:(NSData * _Nonnull)imageData label:(NSString * _Nullable)label metadata:(NSDictionary<NSString *, id> * _Nullable)metadata completion:(void (^ _Nonnull)(NSArray<TVApiError *> * _Nonnull, NSString * _Nullable))completion SWIFT_WARN_UNUSED_RESULT;
- (NSString * _Nonnull)readIdCardInfoWithReadIdCardInfoRequest:(TVCardInfoRequest * _Nonnull)readIdCardInfoRequest completion:(void (^ _Nonnull)(NSArray<TVApiError *> * _Nonnull, NSString * _Nullable))completion SWIFT_WARN_UNUSED_RESULT;
- (NSString * _Nonnull)checkReadIdCardInfoWithRId:(NSString * _Nonnull)rId completion:(void (^ _Nonnull)(NSArray<TVApiError *> * _Nonnull, TVCardInfoResponse * _Nullable))completion SWIFT_WARN_UNUSED_RESULT;
- (NSString * _Nonnull)compareFacesWithImage1Id:(NSString * _Nonnull)image1Id image2Id:(NSString * _Nonnull)image2Id completion:(void (^ _Nonnull)(NSArray<TVApiError *> * _Nonnull, NSString * _Nullable))completion SWIFT_WARN_UNUSED_RESULT;
- (NSString * _Nonnull)checkCompareFacesWithRId:(NSString * _Nonnull)rId completion:(void (^ _Nonnull)(NSArray<TVApiError *> * _Nonnull, TVCompareFacesResponse * _Nullable))completion SWIFT_WARN_UNUSED_RESULT;
- (NSString * _Nonnull)verifyLivenessWithGestures:(NSArray<NSString *> * _Nonnull)gestures imageIds:(NSArray<NSString *> * _Nonnull)imageIds completion:(void (^ _Nonnull)(NSArray<TVApiError *> * _Nonnull, NSString * _Nullable))completion SWIFT_WARN_UNUSED_RESULT;
- (NSString * _Nonnull)checkVerifyLivenessWithRId:(NSString * _Nonnull)rId completion:(void (^ _Nonnull)(NSArray<TVApiError *> * _Nonnull, TVVerifyLivenessResponse * _Nullable))completion SWIFT_WARN_UNUSED_RESULT;
- (NSString * _Nonnull)verifyIdCardSanityWithCardType:(NSString * _Nonnull)cardType image1Id:(NSString * _Nonnull)image1Id image2Id:(NSString * _Nullable)image2Id completion:(void (^ _Nonnull)(NSArray<TVApiError *> * _Nonnull, NSString * _Nullable))completion SWIFT_WARN_UNUSED_RESULT;
- (NSString * _Nonnull)checkVerifyIdCardSanityWithRId:(NSString * _Nonnull)rId completion:(void (^ _Nonnull)(NSArray<TVApiError *> * _Nonnull, TVVerifyIdCardSanityResponse * _Nullable))completion SWIFT_WARN_UNUSED_RESULT;
- (NSString * _Nonnull)verifyPortraitSanityWithImageId:(NSString * _Nonnull)imageId completion:(void (^ _Nonnull)(NSArray<TVApiError *> * _Nonnull, NSString * _Nullable))completion SWIFT_WARN_UNUSED_RESULT;
- (NSString * _Nonnull)checkVerifyPortraitSanityWithRId:(NSString * _Nonnull)rId completion:(void (^ _Nonnull)(NSArray<TVApiError *> * _Nonnull, TVVerifyPortraitSanityResponse * _Nullable))completion SWIFT_WARN_UNUSED_RESULT;
- (void)pollVerifyIdCardSanityWithCardType:(NSString * _Nonnull)cardType image1Id:(NSString * _Nonnull)image1Id image2Id:(NSString * _Nullable)image2Id completion:(void (^ _Nonnull)(NSArray<TVApiError *> * _Nonnull, TVVerifyIdCardSanityResponse * _Nullable))completion;
- (void)pollCompareFacesWithImage1Id:(NSString * _Nonnull)image1Id image2Id:(NSString * _Nonnull)image2Id completion:(void (^ _Nonnull)(NSArray<TVApiError *> * _Nonnull, TVCompareFacesResponse * _Nullable))completion;
- (void)pollReadIdCardInfoWithReadIdCardInfoRequest:(TVCardInfoRequest * _Nonnull)readIdCardInfoRequest completion:(void (^ _Nonnull)(NSArray<TVApiError *> * _Nonnull, TVCardInfoResponse * _Nullable))completion;
- (void)pollVerifyPortraitSanityWithImageId:(NSString * _Nonnull)imageId completion:(void (^ _Nonnull)(NSArray<TVApiError *> * _Nonnull, TVVerifyPortraitSanityResponse * _Nullable))completion;
- (void)pollVerifyLivenessWithGestures:(NSArray<NSString *> * _Nonnull)gestures imageIds:(NSArray<NSString *> * _Nonnull)imageIds completion:(void (^ _Nonnull)(NSArray<TVApiError *> * _Nonnull, TVVerifyLivenessResponse * _Nullable))completion;
- (NSString * _Nonnull)syncCompareFacesWithImage1:(TVRequestImage * _Nonnull)image1 image2:(TVRequestImage * _Nonnull)image2 completion:(void (^ _Nonnull)(NSArray<TVApiError *> * _Nonnull, TVCompareFacesResponse * _Nullable))completion SWIFT_WARN_UNUSED_RESULT;
- (NSString * _Nonnull)syncReadIdCardInfoWithReadIdCardInfoRequest:(TVCardInfoSyncRequest * _Nonnull)readIdCardInfoRequest completion:(void (^ _Nonnull)(NSArray<TVApiError *> * _Nonnull, TVCardInfoResponse * _Nullable))completion SWIFT_WARN_UNUSED_RESULT;
- (NSString * _Nonnull)syncVerifyIdCardSanityWithCardType:(NSString * _Nonnull)cardType image1:(TVRequestImage * _Nonnull)image1 image2:(TVRequestImage * _Nullable)image2 completion:(void (^ _Nonnull)(NSArray<TVApiError *> * _Nonnull, TVVerifyIdCardSanityResponse * _Nullable))completion SWIFT_WARN_UNUSED_RESULT;
- (NSString * _Nonnull)syncVerifyPortraitSanityWithImage:(TVRequestImage * _Nonnull)image completion:(void (^ _Nonnull)(NSArray<TVApiError *> * _Nonnull, TVVerifyPortraitSanityResponse * _Nullable))completion SWIFT_WARN_UNUSED_RESULT;
- (NSString * _Nonnull)syncVerifyLivenessWithGestures:(NSArray<TVRequestGestureImage *> * _Nonnull)gestures images:(NSArray<TVRequestImage *> * _Nonnull)images videos:(NSArray<TVRequestVideo *> * _Nonnull)videos metadata:(NSDictionary<NSString *, id> * _Nullable)metadata completion:(void (^ _Nonnull)(NSArray<TVApiError *> * _Nonnull, TVVerifyLivenessResponse * _Nullable))completion SWIFT_WARN_UNUSED_RESULT;
- (NSString * _Nonnull)syncDetectIdCardTamperingWithCardTamperingRequest:(TVCardTamperingRequest * _Nonnull)cardTamperingRequest completion:(void (^ _Nonnull)(NSArray<TVApiError *> * _Nonnull, TVDetectIdCardTamperingResponse * _Nullable))completion SWIFT_WARN_UNUSED_RESULT;
- (NSString * _Nonnull)createTransactionWithReferenceId:(NSString * _Nullable)referenceId completion:(void (^ _Nonnull)(NSArray<TVApiError *> * _Nonnull, NSString * _Nullable))completion SWIFT_WARN_UNUSED_RESULT;
- (NSString * _Nonnull)endTransactionWithTransactionId:(NSString * _Nullable)transactionId completion:(void (^ _Nonnull)(NSArray<TVApiError *> * _Nonnull))completion SWIFT_WARN_UNUSED_RESULT;
- (void)setTransactionId:(NSString * _Nullable)transactionId;
- (NSString * _Nullable)getTransactionId SWIFT_WARN_UNUSED_RESULT;
- (NSString * _Nonnull)getImageWithImageId:(NSString * _Nonnull)imageId completion:(void (^ _Nonnull)(NSArray<TVApiError *> * _Nonnull, UIImage * _Nullable))completion SWIFT_WARN_UNUSED_RESULT;
- (NSString * _Nonnull)logEventWithEvent:(TVLogRequest * _Nonnull)event completion:(void (^ _Nonnull)(NSArray<TVApiError *> * _Nonnull))completion SWIFT_WARN_UNUSED_RESULT;
- (NSString * _Nonnull)requestWithUrl:(NSString * _Nonnull)url completion:(void (^ _Nonnull)(NSArray<TVApiError *> * _Nonnull, NSData * _Nullable))completion SWIFT_WARN_UNUSED_RESULT;
@end





@class NSURLSession;
@class NSURLAuthenticationChallenge;
@class NSURLCredential;

@interface TVAPIClient (SWIFT_EXTENSION(TrustVisionAPI)) <NSURLSessionDelegate>
- (void)URLSession:(NSURLSession * _Nonnull)session didReceiveChallenge:(NSURLAuthenticationChallenge * _Nonnull)challenge completionHandler:(void (^ _Nonnull)(NSURLSessionAuthChallengeDisposition, NSURLCredential * _Nullable))completionHandler;
@end






SWIFT_CLASS("_TtC14TrustVisionAPI14TVApiClientLog")
@interface TVApiClientLog : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC14TrustVisionAPI18TVApiClientFileLog")
@interface TVApiClientFileLog : TVApiClientLog
@end



SWIFT_CLASS("_TtC14TrustVisionAPI10TVApiError")
@interface TVApiError : NSObject
@property (nonatomic, readonly, copy) NSString * _Nonnull errorCode;
@property (nonatomic, readonly, copy) NSDictionary<NSString *, id> * _Nullable detail;
@property (nonatomic, readonly, copy) NSString * _Nullable message;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

enum TVPollingResult : NSInteger;

SWIFT_CLASS("_TtC14TrustVisionAPI13TVBasePolling")
@interface TVBasePolling : NSObject
@property (nonatomic) enum TVPollingResult status;
@property (nonatomic, copy) NSString * _Nullable requestId;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC14TrustVisionAPI17TVCardInfoRequest")
@interface TVCardInfoRequest : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@class Image;
@class Info;

SWIFT_CLASS("_TtC14TrustVisionAPI18TVCardInfoResponse")
@interface TVCardInfoResponse : TVBasePolling
@property (nonatomic, strong) Image * _Nullable image1;
@property (nonatomic, strong) Image * _Nullable image2;
@property (nonatomic, copy) NSArray<Info *> * _Nonnull cardInformation;
@end

@class Ocr;

SWIFT_CLASS("_TtCC14TrustVisionAPI18TVCardInfoResponse5Image")
@interface Image : NSObject
@property (nonatomic, copy) NSString * _Nullable id;
@property (nonatomic, copy) NSString * _Nullable transformedImageId;
@property (nonatomic, copy) NSArray<Info *> * _Nonnull qr;
@property (nonatomic, copy) NSArray<Ocr *> * _Nonnull ocr;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@class TVPoint;

SWIFT_CLASS("_TtCC14TrustVisionAPI18TVCardInfoResponse3Ocr")
@interface Ocr : NSObject
@property (nonatomic, copy) NSString * _Nullable text;
@property (nonatomic, copy) NSArray<TVPoint *> * _Nonnull boundingBox;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtCC14TrustVisionAPI18TVCardInfoResponse4Info")
@interface Info : NSObject
@property (nonatomic, copy) NSString * _Nullable field;
@property (nonatomic, copy) NSString * _Nullable value;
@property (nonatomic, copy) NSString * _Nullable confidenceVerdict;
@property (nonatomic) float confidenceScore;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC14TrustVisionAPI21TVCardInfoSyncRequest")
@interface TVCardInfoSyncRequest : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC14TrustVisionAPI22TVCardTamperingRequest")
@interface TVCardTamperingRequest : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@class CardType;
@class Settings;

SWIFT_CLASS("_TtC14TrustVisionAPI24TVClientSettingsResponse")
@interface TVClientSettingsResponse : NSObject
@property (nonatomic, copy) NSString * _Nullable country;
@property (nonatomic, copy) NSArray<CardType *> * _Nonnull cardTypes;
@property (nonatomic, strong) Settings * _Nullable settings;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

typedef SWIFT_ENUM(NSInteger, Orientation, open) {
  OrientationHorizontal = 0,
  OrientationVertical = 1,
};

typedef SWIFT_ENUM(NSInteger, FaceTrackingMethod, open) {
  FaceTrackingMethodAllFlow = 0,
  FaceTrackingMethodEachGesture = 1,
};


SWIFT_CLASS("_TtCC14TrustVisionAPI24TVClientSettingsResponse19FaceTrackingSetting")
@interface FaceTrackingSetting : NSObject
@property (nonatomic) BOOL enable;
@property (nonatomic) NSInteger maxWarningTime;
@property (nonatomic) float terminateThreshold;
@property (nonatomic) float warningThrehold;
@property (nonatomic) enum FaceTrackingMethod method;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtCC14TrustVisionAPI24TVClientSettingsResponse22LimitTimeLivenessCheck")
@interface LimitTimeLivenessCheck : NSObject
@property (nonatomic) BOOL enable;
@property (nonatomic) NSInteger livenessCheckTimeoutSecond;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtCC14TrustVisionAPI24TVClientSettingsResponse18TerminiateIfNoFace")
@interface TerminiateIfNoFace : NSObject
@property (nonatomic) BOOL enable;
@property (nonatomic) NSInteger maxInvalidFrames;
@property (nonatomic) NSInteger maxIntervalTimeMs;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtCC14TrustVisionAPI24TVClientSettingsResponse11RecordVideo")
@interface RecordVideo : NSObject
@property (nonatomic) BOOL enable;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtCC14TrustVisionAPI24TVClientSettingsResponse17SaveEncodedFrames")
@interface SaveEncodedFrames : NSObject
@property (nonatomic) BOOL enable;
@property (nonatomic) NSInteger framesIntervalMs;
@property (nonatomic) NSInteger framesBatchLen;
@property (nonatomic) BOOL enableLogging;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtCC14TrustVisionAPI24TVClientSettingsResponse21ActiveLivenessSetting")
@interface ActiveLivenessSetting : NSObject
@property (nonatomic, strong) FaceTrackingSetting * _Nullable faceTrackingSetting;
@property (nonatomic, strong) LimitTimeLivenessCheck * _Nullable limitTimeLivenessCheck;
@property (nonatomic, strong) RecordVideo * _Nullable recordVideo;
@property (nonatomic, strong) SaveEncodedFrames * _Nullable saveEncodedFrames;
@property (nonatomic, strong) TerminiateIfNoFace * _Nullable terminateIfNoFace;
@property (nonatomic) NSInteger flowIntervalTimeMs;
@property (nonatomic) BOOL showGestureArrow;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtCC14TrustVisionAPI24TVClientSettingsResponse11IdDetection")
@interface IdDetection : NSObject
@property (nonatomic) BOOL enable;
@end


SWIFT_CLASS("_TtCC14TrustVisionAPI24TVClientSettingsResponse11IdBlurCheck")
@interface IdBlurCheck : NSObject
@property (nonatomic) BOOL enable;
@property (nonatomic) double threshold;
@end


SWIFT_CLASS("_TtCC14TrustVisionAPI24TVClientSettingsResponse12IdGlareCheck")
@interface IdGlareCheck : NSObject
@property (nonatomic) BOOL enable;
@property (nonatomic) double threshold;
@end


SWIFT_CLASS("_TtCC14TrustVisionAPI24TVClientSettingsResponse13IdAutoCapture")
@interface IdAutoCapture : NSObject
@property (nonatomic) BOOL enable;
@property (nonatomic) BOOL showCaptureButton;
@property (nonatomic) NSInteger waitForBestImageTimeMs;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtCC14TrustVisionAPI24TVClientSettingsResponse12IdQrSettings")
@interface IdQrSettings : NSObject
@property (nonatomic) BOOL enable;
@property (nonatomic) NSInteger limitTimeSecond;
@end


SWIFT_CLASS("_TtCC14TrustVisionAPI24TVClientSettingsResponse18IdDetectionSetting")
@interface IdDetectionSetting : NSObject
@property (nonatomic, strong) IdDetection * _Nullable idDetection;
@property (nonatomic, strong) IdBlurCheck * _Nullable blurCheck;
@property (nonatomic, strong) IdGlareCheck * _Nullable glareCheck;
@property (nonatomic, strong) IdAutoCapture * _Nullable idAutoCapture;
@property (nonatomic) BOOL disableCaptureButtonIfAlert;
@property (nonatomic, strong) SaveEncodedFrames * _Nullable saveFrameSetting;
@property (nonatomic, strong) LimitTimeLivenessCheck * _Nullable limitTimeSetting;
@property (nonatomic) NSInteger flowIntervalTimeMs;
@property (nonatomic, strong) IdQrSettings * _Nullable qrSettings;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtCC14TrustVisionAPI24TVClientSettingsResponse21LivenessVerticalCheck")
@interface LivenessVerticalCheck : NSObject
@property (nonatomic) BOOL enable;
@property (nonatomic) NSInteger thresholdInDegree;
@end


SWIFT_CLASS("_TtCC14TrustVisionAPI24TVClientSettingsResponse15LivenessSetting")
@interface LivenessSetting : NSObject
@property (nonatomic, strong) LivenessVerticalCheck * _Nonnull verticalCheck;
@end


SWIFT_CLASS("_TtCC14TrustVisionAPI24TVClientSettingsResponse16ServerLogSetting")
@interface ServerLogSetting : NSObject
@property (nonatomic) BOOL enable;
@end


SWIFT_CLASS("_TtCC14TrustVisionAPI24TVClientSettingsResponse11SdkSettings")
@interface SdkSettings : NSObject
@property (nonatomic, strong) ServerLogSetting * _Nullable serverLogSetting;
@property (nonatomic, strong) ActiveLivenessSetting * _Nullable activeLivenessSetting;
@property (nonatomic, strong) IdDetectionSetting * _Nullable idDetectionSetting;
@property (nonatomic, strong) LivenessSetting * _Nullable livenessSetting;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

enum TVScanQrMode : NSInteger;

SWIFT_CLASS("_TtCC14TrustVisionAPI24TVClientSettingsResponse8Settings")
@interface Settings : NSObject
@property (nonatomic) enum TVScanQrMode scanQrMode;
@property (nonatomic, copy) NSArray<NSString *> * _Nonnull cameraOptions;
@property (nonatomic, copy) NSArray<NSString *> * _Nonnull livenessOptions;
@property (nonatomic) BOOL enableMultipleFaces;
@property (nonatomic) BOOL enableVerifyPortraitSanity;
@property (nonatomic) BOOL enableVerifyIdSanity;
@property (nonatomic) BOOL supportTransaction;
@property (nonatomic) BOOL enableDetectIdCardTampering;
@property (nonatomic, strong) SdkSettings * _Nullable sdkSettings;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@class TVQR;

SWIFT_CLASS("_TtCC14TrustVisionAPI24TVClientSettingsResponse8CardType")
@interface CardType : NSObject
@property (nonatomic, copy) NSString * _Nullable code;
@property (nonatomic, copy) NSString * _Nullable name;
@property (nonatomic) enum Orientation orientation;
@property (nonatomic) BOOL hasBackSide;
@property (nonatomic, strong) TVQR * _Nullable frontQr;
@property (nonatomic, strong) TVQR * _Nullable backQr;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@class FaceImage;
@class CompareFace;

SWIFT_CLASS("_TtC14TrustVisionAPI22TVCompareFacesResponse")
@interface TVCompareFacesResponse : TVBasePolling
@property (nonatomic, strong) FaceImage * _Nullable image1;
@property (nonatomic, strong) FaceImage * _Nullable image2;
@property (nonatomic, copy) NSArray<CompareFace *> * _Nonnull compareFaces;
@end

enum TVCompareFaceResult : NSInteger;

SWIFT_CLASS("_TtCC14TrustVisionAPI22TVCompareFacesResponse11CompareFace")
@interface CompareFace : NSObject
@property (nonatomic) float confidence;
@property (nonatomic) enum TVCompareFaceResult result;
@property (nonatomic, copy) NSString * _Nullable face1Id;
@property (nonatomic, copy) NSString * _Nullable face2Id;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

typedef SWIFT_ENUM(NSInteger, TVCompareFaceResult, open) {
  TVCompareFaceResultMatched = 0,
  TVCompareFaceResultUnmatched = 1,
  TVCompareFaceResultUnsure = 2,
};

@class Face;

SWIFT_CLASS("_TtCC14TrustVisionAPI22TVCompareFacesResponse9FaceImage")
@interface FaceImage : NSObject
@property (nonatomic, copy) NSString * _Nullable id;
@property (nonatomic, copy) NSString * _Nullable transformed_image_id;
@property (nonatomic, copy) NSArray<Face *> * _Nonnull faces;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@class BoundingBox;

SWIFT_CLASS("_TtCC14TrustVisionAPI22TVCompareFacesResponse4Face")
@interface Face : NSObject
@property (nonatomic, copy) NSString * _Nullable id;
@property (nonatomic, strong) BoundingBox * _Nullable boundingBox;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtCC14TrustVisionAPI22TVCompareFacesResponse11BoundingBox")
@interface BoundingBox : NSObject
@property (nonatomic) NSInteger top;
@property (nonatomic) NSInteger right;
@property (nonatomic) NSInteger bottom;
@property (nonatomic) NSInteger left;
@property (nonatomic) NSInteger angle;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@class TVIdCardTampering;

SWIFT_CLASS("_TtC14TrustVisionAPI31TVDetectIdCardTamperingResponse")
@interface TVDetectIdCardTamperingResponse : TVBasePolling
@property (nonatomic, strong) TVIdCardTampering * _Nullable cardTampering;
@property (nonatomic, copy) NSString * _Nullable imageId;
@property (nonatomic, copy) NSString * _Nullable image2Id;
@end

enum TVQRType : NSInteger;

SWIFT_CLASS("_TtC14TrustVisionAPI12TVEnumParser")
@interface TVEnumParser : NSObject
+ (enum TVScanQrMode)TVScanQrModeWithStringValue:(NSString * _Nonnull)stringValue SWIFT_WARN_UNUSED_RESULT;
+ (enum TVQRType)TVQRTypeWithStringValue:(NSString * _Nonnull)stringValue SWIFT_WARN_UNUSED_RESULT;
+ (enum Orientation)OrientationWithStringValue:(NSString * _Nonnull)stringValue SWIFT_WARN_UNUSED_RESULT;
+ (enum TVCompareFaceResult)TVCompareFaceResultWithStringValue:(NSString * _Nonnull)stringValue SWIFT_WARN_UNUSED_RESULT;
+ (enum FaceTrackingMethod)TVFaceTrackingMethodWithStringValue:(NSString * _Nonnull)stringValue SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC14TrustVisionAPI23TVIDCardTamperingDetail")
@interface TVIDCardTamperingDetail : NSObject
@property (nonatomic, copy) NSString * _Nullable name;
@property (nonatomic) float score;
@property (nonatomic, copy) NSString * _Nullable verdict;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC14TrustVisionAPI17TVIdCardTampering")
@interface TVIdCardTampering : NSObject
@property (nonatomic, copy) NSString * _Nullable verdict;
@property (nonatomic) float score;
@property (nonatomic, copy) NSArray<TVIDCardTamperingDetail *> * _Nullable details;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class CardBox;

SWIFT_CLASS("_TtC14TrustVisionAPI15TVImageResponse")
@interface TVImageResponse : NSObject
@property (nonatomic, copy) NSString * _Nonnull id;
@property (nonatomic, copy) NSString * _Nullable transformedImageId;
@property (nonatomic, strong) CardBox * _Nullable cardBox;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtCC14TrustVisionAPI15TVImageResponse7CardBox")
@interface CardBox : NSObject
@property (nonatomic, strong) TVPoint * _Nonnull topLeft;
@property (nonatomic, strong) TVPoint * _Nonnull topRight;
@property (nonatomic, strong) TVPoint * _Nonnull bottomLeft;
@property (nonatomic, strong) TVPoint * _Nonnull bottomRight;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC14TrustVisionAPI12TVLogRequest")
@interface TVLogRequest : NSObject
- (NSDictionary<NSString *, id> * _Nullable)toJsonDict SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC14TrustVisionAPI7TVPoint")
@interface TVPoint : NSObject
@property (nonatomic) NSInteger x;
@property (nonatomic) NSInteger y;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) TVPoint * _Nonnull zero;)
+ (TVPoint * _Nonnull)zero SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

typedef SWIFT_ENUM(NSInteger, TVPollingResult, open) {
  TVPollingResultProcessing = 0,
  TVPollingResultSuccess = 1,
  TVPollingResultFailure = 2,
};


SWIFT_CLASS("_TtC14TrustVisionAPI4TVQR")
@interface TVQR : NSObject
@property (nonatomic) BOOL exist;
@property (nonatomic) enum TVQRType type;
@property (nonatomic) float widthHeightRatio;
- (nonnull instancetype)initWithExist:(BOOL)exist type:(enum TVQRType)type widthHeightRatio:(float)widthHeightRatio OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

typedef SWIFT_ENUM(NSInteger, TVQRType, open) {
  TVQRTypeQrCode = 0,
  TVQRTypeBarCode = 1,
};


SWIFT_CLASS("_TtC14TrustVisionAPI21TVRequestGestureImage")
@interface TVRequestGestureImage : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

typedef SWIFT_ENUM(NSInteger, RequestGestureType, open) {
  RequestGestureTypeUp = 0,
  RequestGestureTypeDown = 1,
  RequestGestureTypeLeft = 2,
  RequestGestureTypeRight = 3,
  RequestGestureTypeFrontal = 4,
};


SWIFT_CLASS("_TtC14TrustVisionAPI14TVRequestImage")
@interface TVRequestImage : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC14TrustVisionAPI14TVRequestVideo")
@interface TVRequestVideo : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC14TrustVisionAPI19TVRequestVideoFrame")
@interface TVRequestVideoFrame : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC14TrustVisionAPI8TVSanity")
@interface TVSanity : NSObject
@property (nonatomic, copy) NSString * _Nullable verdict;
@property (nonatomic) float score;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

typedef SWIFT_ENUM(NSInteger, TVScanQrMode, open) {
  TVScanQrModeNone = 0,
  TVScanQrModeSeparateStep = 1,
  TVScanQrModeWithCard = 2,
};


SWIFT_CLASS("_TtC14TrustVisionAPI21TVTransactionResponse")
@interface TVTransactionResponse : NSObject
@property (nonatomic, copy) NSString * _Nullable id;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC14TrustVisionAPI28TVVerifyIdCardSanityResponse")
@interface TVVerifyIdCardSanityResponse : TVBasePolling
@property (nonatomic, strong) TVImageResponse * _Nullable image1;
@property (nonatomic, strong) TVImageResponse * _Nullable image2;
@property (nonatomic, strong) TVSanity * _Nullable cardSanity;
@end


SWIFT_CLASS("_TtC14TrustVisionAPI24TVVerifyLivenessResponse")
@interface TVVerifyLivenessResponse : TVBasePolling
@property (nonatomic) BOOL isLive;
@property (nonatomic) float score;
@end


SWIFT_CLASS("_TtC14TrustVisionAPI30TVVerifyPortraitSanityResponse")
@interface TVVerifyPortraitSanityResponse : TVBasePolling
@property (nonatomic, strong) TVSanity * _Nullable portraitSanity;
@end

#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#pragma clang diagnostic pop

#elif defined(__i386__) && __i386__
// Generated by Apple Swift version 5.2.4 (swiftlang-1103.0.32.9 clang-1103.0.32.53)
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wgcc-compat"

#if !defined(__has_include)
# define __has_include(x) 0
#endif
#if !defined(__has_attribute)
# define __has_attribute(x) 0
#endif
#if !defined(__has_feature)
# define __has_feature(x) 0
#endif
#if !defined(__has_warning)
# define __has_warning(x) 0
#endif

#if __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#include <Foundation/Foundation.h>
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus)
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...)
# endif
#endif

#if __has_attribute(objc_runtime_name)
# define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
#else
# define SWIFT_RUNTIME_NAME(X)
#endif
#if __has_attribute(swift_name)
# define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
#else
# define SWIFT_COMPILE_NAME(X)
#endif
#if __has_attribute(objc_method_family)
# define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
#else
# define SWIFT_METHOD_FAMILY(X)
#endif
#if __has_attribute(noescape)
# define SWIFT_NOESCAPE __attribute__((noescape))
#else
# define SWIFT_NOESCAPE
#endif
#if __has_attribute(ns_consumed)
# define SWIFT_RELEASES_ARGUMENT __attribute__((ns_consumed))
#else
# define SWIFT_RELEASES_ARGUMENT
#endif
#if __has_attribute(warn_unused_result)
# define SWIFT_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
#else
# define SWIFT_WARN_UNUSED_RESULT
#endif
#if __has_attribute(noreturn)
# define SWIFT_NORETURN __attribute__((noreturn))
#else
# define SWIFT_NORETURN
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA
#endif
#if !defined(SWIFT_CLASS)
# if __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif
#if !defined(SWIFT_RESILIENT_CLASS)
# if __has_attribute(objc_class_stub)
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME) __attribute__((objc_class_stub))
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_class_stub)) SWIFT_CLASS_NAMED(SWIFT_NAME)
# else
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME)
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) SWIFT_CLASS_NAMED(SWIFT_NAME)
# endif
#endif

#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif

#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif

#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER
# endif
#endif
#if !defined(SWIFT_ENUM_ATTR)
# if defined(__has_attribute) && __has_attribute(enum_extensibility)
#  define SWIFT_ENUM_ATTR(_extensibility) __attribute__((enum_extensibility(_extensibility)))
# else
#  define SWIFT_ENUM_ATTR(_extensibility)
# endif
#endif
#if !defined(SWIFT_ENUM)
# define SWIFT_ENUM(_type, _name, _extensibility) enum _name : _type _name; enum SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# if __has_feature(generalized_swift_name)
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# else
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if !defined(SWIFT_UNAVAILABLE_MSG)
# define SWIFT_UNAVAILABLE_MSG(msg) __attribute__((unavailable(msg)))
#endif
#if !defined(SWIFT_AVAILABILITY)
# define SWIFT_AVAILABILITY(plat, ...) __attribute__((availability(plat, __VA_ARGS__)))
#endif
#if !defined(SWIFT_WEAK_IMPORT)
# define SWIFT_WEAK_IMPORT __attribute__((weak_import))
#endif
#if !defined(SWIFT_DEPRECATED)
# define SWIFT_DEPRECATED __attribute__((deprecated))
#endif
#if !defined(SWIFT_DEPRECATED_MSG)
# define SWIFT_DEPRECATED_MSG(...) __attribute__((deprecated(__VA_ARGS__)))
#endif
#if __has_feature(attribute_diagnose_if_objc)
# define SWIFT_DEPRECATED_OBJC(Msg) __attribute__((diagnose_if(1, Msg, "warning")))
#else
# define SWIFT_DEPRECATED_OBJC(Msg) SWIFT_DEPRECATED_MSG(Msg)
#endif
#if !defined(IBSegueAction)
# define IBSegueAction
#endif
#if __has_feature(modules)
#if __has_warning("-Watimport-in-framework-header")
#pragma clang diagnostic ignored "-Watimport-in-framework-header"
#endif
@import Foundation;
@import ObjectiveC;
#endif

#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="TrustVisionAPI",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif


SWIFT_PROTOCOL("_TtP14TrustVisionAPI18DeviceInfoProtocol_")
@protocol DeviceInfoProtocol
- (NSString * _Nonnull)getPlatform SWIFT_WARN_UNUSED_RESULT;
- (NSString * _Nonnull)getOSVersion SWIFT_WARN_UNUSED_RESULT;
- (NSString * _Nonnull)getSDKVersion SWIFT_WARN_UNUSED_RESULT;
- (NSString * _Nonnull)getDeviceModel SWIFT_WARN_UNUSED_RESULT;
@end

@class TVApiError;
@class TVClientSettingsResponse;
@class TVRequestVideoFrame;
@class TVCardInfoRequest;
@class TVCardInfoResponse;
@class TVCompareFacesResponse;
@class TVVerifyLivenessResponse;
@class TVVerifyIdCardSanityResponse;
@class TVVerifyPortraitSanityResponse;
@class TVRequestImage;
@class TVCardInfoSyncRequest;
@class TVRequestGestureImage;
@class TVRequestVideo;
@class TVCardTamperingRequest;
@class TVDetectIdCardTamperingResponse;
@class UIImage;
@class TVLogRequest;

SWIFT_CLASS("_TtC14TrustVisionAPI11TVAPIClient")
@interface TVAPIClient : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (void)setupWithBaseUrl:(NSString * _Nullable)baseUrl deviceInfo:(id <DeviceInfoProtocol> _Nonnull)deviceInfo getAuthorization:(void (^ _Nonnull)(NSString * _Nullable, NSString * _Nullable, SWIFT_NOESCAPE void (^ _Nonnull)(NSString * _Nullable, NSString * _Nullable, NSString * _Nullable)))getAuthorization errorHandler:(void (^ _Nullable)(NSArray<TVApiError *> * _Nonnull))errorHandler;
- (NSString * _Nonnull)getClientSettingsWithCompletion:(void (^ _Nonnull)(NSArray<TVApiError *> * _Nonnull, TVClientSettingsResponse * _Nullable))completion SWIFT_WARN_UNUSED_RESULT;
- (NSString * _Nonnull)uploadVideoWithVideoData:(NSData * _Nullable)videoData frames:(NSArray<TVRequestVideoFrame *> * _Nullable)frames label:(NSString * _Nullable)label metadata:(NSDictionary<NSString *, id> * _Nullable)metadata completion:(void (^ _Nonnull)(NSArray<TVApiError *> * _Nonnull, NSString * _Nullable))completion SWIFT_WARN_UNUSED_RESULT;
- (NSString * _Nonnull)uploadImageWithImageData:(NSData * _Nonnull)imageData label:(NSString * _Nullable)label metadata:(NSDictionary<NSString *, id> * _Nullable)metadata completion:(void (^ _Nonnull)(NSArray<TVApiError *> * _Nonnull, NSString * _Nullable))completion SWIFT_WARN_UNUSED_RESULT;
- (NSString * _Nonnull)readIdCardInfoWithReadIdCardInfoRequest:(TVCardInfoRequest * _Nonnull)readIdCardInfoRequest completion:(void (^ _Nonnull)(NSArray<TVApiError *> * _Nonnull, NSString * _Nullable))completion SWIFT_WARN_UNUSED_RESULT;
- (NSString * _Nonnull)checkReadIdCardInfoWithRId:(NSString * _Nonnull)rId completion:(void (^ _Nonnull)(NSArray<TVApiError *> * _Nonnull, TVCardInfoResponse * _Nullable))completion SWIFT_WARN_UNUSED_RESULT;
- (NSString * _Nonnull)compareFacesWithImage1Id:(NSString * _Nonnull)image1Id image2Id:(NSString * _Nonnull)image2Id completion:(void (^ _Nonnull)(NSArray<TVApiError *> * _Nonnull, NSString * _Nullable))completion SWIFT_WARN_UNUSED_RESULT;
- (NSString * _Nonnull)checkCompareFacesWithRId:(NSString * _Nonnull)rId completion:(void (^ _Nonnull)(NSArray<TVApiError *> * _Nonnull, TVCompareFacesResponse * _Nullable))completion SWIFT_WARN_UNUSED_RESULT;
- (NSString * _Nonnull)verifyLivenessWithGestures:(NSArray<NSString *> * _Nonnull)gestures imageIds:(NSArray<NSString *> * _Nonnull)imageIds completion:(void (^ _Nonnull)(NSArray<TVApiError *> * _Nonnull, NSString * _Nullable))completion SWIFT_WARN_UNUSED_RESULT;
- (NSString * _Nonnull)checkVerifyLivenessWithRId:(NSString * _Nonnull)rId completion:(void (^ _Nonnull)(NSArray<TVApiError *> * _Nonnull, TVVerifyLivenessResponse * _Nullable))completion SWIFT_WARN_UNUSED_RESULT;
- (NSString * _Nonnull)verifyIdCardSanityWithCardType:(NSString * _Nonnull)cardType image1Id:(NSString * _Nonnull)image1Id image2Id:(NSString * _Nullable)image2Id completion:(void (^ _Nonnull)(NSArray<TVApiError *> * _Nonnull, NSString * _Nullable))completion SWIFT_WARN_UNUSED_RESULT;
- (NSString * _Nonnull)checkVerifyIdCardSanityWithRId:(NSString * _Nonnull)rId completion:(void (^ _Nonnull)(NSArray<TVApiError *> * _Nonnull, TVVerifyIdCardSanityResponse * _Nullable))completion SWIFT_WARN_UNUSED_RESULT;
- (NSString * _Nonnull)verifyPortraitSanityWithImageId:(NSString * _Nonnull)imageId completion:(void (^ _Nonnull)(NSArray<TVApiError *> * _Nonnull, NSString * _Nullable))completion SWIFT_WARN_UNUSED_RESULT;
- (NSString * _Nonnull)checkVerifyPortraitSanityWithRId:(NSString * _Nonnull)rId completion:(void (^ _Nonnull)(NSArray<TVApiError *> * _Nonnull, TVVerifyPortraitSanityResponse * _Nullable))completion SWIFT_WARN_UNUSED_RESULT;
- (void)pollVerifyIdCardSanityWithCardType:(NSString * _Nonnull)cardType image1Id:(NSString * _Nonnull)image1Id image2Id:(NSString * _Nullable)image2Id completion:(void (^ _Nonnull)(NSArray<TVApiError *> * _Nonnull, TVVerifyIdCardSanityResponse * _Nullable))completion;
- (void)pollCompareFacesWithImage1Id:(NSString * _Nonnull)image1Id image2Id:(NSString * _Nonnull)image2Id completion:(void (^ _Nonnull)(NSArray<TVApiError *> * _Nonnull, TVCompareFacesResponse * _Nullable))completion;
- (void)pollReadIdCardInfoWithReadIdCardInfoRequest:(TVCardInfoRequest * _Nonnull)readIdCardInfoRequest completion:(void (^ _Nonnull)(NSArray<TVApiError *> * _Nonnull, TVCardInfoResponse * _Nullable))completion;
- (void)pollVerifyPortraitSanityWithImageId:(NSString * _Nonnull)imageId completion:(void (^ _Nonnull)(NSArray<TVApiError *> * _Nonnull, TVVerifyPortraitSanityResponse * _Nullable))completion;
- (void)pollVerifyLivenessWithGestures:(NSArray<NSString *> * _Nonnull)gestures imageIds:(NSArray<NSString *> * _Nonnull)imageIds completion:(void (^ _Nonnull)(NSArray<TVApiError *> * _Nonnull, TVVerifyLivenessResponse * _Nullable))completion;
- (NSString * _Nonnull)syncCompareFacesWithImage1:(TVRequestImage * _Nonnull)image1 image2:(TVRequestImage * _Nonnull)image2 completion:(void (^ _Nonnull)(NSArray<TVApiError *> * _Nonnull, TVCompareFacesResponse * _Nullable))completion SWIFT_WARN_UNUSED_RESULT;
- (NSString * _Nonnull)syncReadIdCardInfoWithReadIdCardInfoRequest:(TVCardInfoSyncRequest * _Nonnull)readIdCardInfoRequest completion:(void (^ _Nonnull)(NSArray<TVApiError *> * _Nonnull, TVCardInfoResponse * _Nullable))completion SWIFT_WARN_UNUSED_RESULT;
- (NSString * _Nonnull)syncVerifyIdCardSanityWithCardType:(NSString * _Nonnull)cardType image1:(TVRequestImage * _Nonnull)image1 image2:(TVRequestImage * _Nullable)image2 completion:(void (^ _Nonnull)(NSArray<TVApiError *> * _Nonnull, TVVerifyIdCardSanityResponse * _Nullable))completion SWIFT_WARN_UNUSED_RESULT;
- (NSString * _Nonnull)syncVerifyPortraitSanityWithImage:(TVRequestImage * _Nonnull)image completion:(void (^ _Nonnull)(NSArray<TVApiError *> * _Nonnull, TVVerifyPortraitSanityResponse * _Nullable))completion SWIFT_WARN_UNUSED_RESULT;
- (NSString * _Nonnull)syncVerifyLivenessWithGestures:(NSArray<TVRequestGestureImage *> * _Nonnull)gestures images:(NSArray<TVRequestImage *> * _Nonnull)images videos:(NSArray<TVRequestVideo *> * _Nonnull)videos metadata:(NSDictionary<NSString *, id> * _Nullable)metadata completion:(void (^ _Nonnull)(NSArray<TVApiError *> * _Nonnull, TVVerifyLivenessResponse * _Nullable))completion SWIFT_WARN_UNUSED_RESULT;
- (NSString * _Nonnull)syncDetectIdCardTamperingWithCardTamperingRequest:(TVCardTamperingRequest * _Nonnull)cardTamperingRequest completion:(void (^ _Nonnull)(NSArray<TVApiError *> * _Nonnull, TVDetectIdCardTamperingResponse * _Nullable))completion SWIFT_WARN_UNUSED_RESULT;
- (NSString * _Nonnull)createTransactionWithReferenceId:(NSString * _Nullable)referenceId completion:(void (^ _Nonnull)(NSArray<TVApiError *> * _Nonnull, NSString * _Nullable))completion SWIFT_WARN_UNUSED_RESULT;
- (NSString * _Nonnull)endTransactionWithTransactionId:(NSString * _Nullable)transactionId completion:(void (^ _Nonnull)(NSArray<TVApiError *> * _Nonnull))completion SWIFT_WARN_UNUSED_RESULT;
- (void)setTransactionId:(NSString * _Nullable)transactionId;
- (NSString * _Nullable)getTransactionId SWIFT_WARN_UNUSED_RESULT;
- (NSString * _Nonnull)getImageWithImageId:(NSString * _Nonnull)imageId completion:(void (^ _Nonnull)(NSArray<TVApiError *> * _Nonnull, UIImage * _Nullable))completion SWIFT_WARN_UNUSED_RESULT;
- (NSString * _Nonnull)logEventWithEvent:(TVLogRequest * _Nonnull)event completion:(void (^ _Nonnull)(NSArray<TVApiError *> * _Nonnull))completion SWIFT_WARN_UNUSED_RESULT;
- (NSString * _Nonnull)requestWithUrl:(NSString * _Nonnull)url completion:(void (^ _Nonnull)(NSArray<TVApiError *> * _Nonnull, NSData * _Nullable))completion SWIFT_WARN_UNUSED_RESULT;
@end





@class NSURLSession;
@class NSURLAuthenticationChallenge;
@class NSURLCredential;

@interface TVAPIClient (SWIFT_EXTENSION(TrustVisionAPI)) <NSURLSessionDelegate>
- (void)URLSession:(NSURLSession * _Nonnull)session didReceiveChallenge:(NSURLAuthenticationChallenge * _Nonnull)challenge completionHandler:(void (^ _Nonnull)(NSURLSessionAuthChallengeDisposition, NSURLCredential * _Nullable))completionHandler;
@end






SWIFT_CLASS("_TtC14TrustVisionAPI14TVApiClientLog")
@interface TVApiClientLog : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC14TrustVisionAPI18TVApiClientFileLog")
@interface TVApiClientFileLog : TVApiClientLog
@end



SWIFT_CLASS("_TtC14TrustVisionAPI10TVApiError")
@interface TVApiError : NSObject
@property (nonatomic, readonly, copy) NSString * _Nonnull errorCode;
@property (nonatomic, readonly, copy) NSDictionary<NSString *, id> * _Nullable detail;
@property (nonatomic, readonly, copy) NSString * _Nullable message;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

enum TVPollingResult : NSInteger;

SWIFT_CLASS("_TtC14TrustVisionAPI13TVBasePolling")
@interface TVBasePolling : NSObject
@property (nonatomic) enum TVPollingResult status;
@property (nonatomic, copy) NSString * _Nullable requestId;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC14TrustVisionAPI17TVCardInfoRequest")
@interface TVCardInfoRequest : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@class Image;
@class Info;

SWIFT_CLASS("_TtC14TrustVisionAPI18TVCardInfoResponse")
@interface TVCardInfoResponse : TVBasePolling
@property (nonatomic, strong) Image * _Nullable image1;
@property (nonatomic, strong) Image * _Nullable image2;
@property (nonatomic, copy) NSArray<Info *> * _Nonnull cardInformation;
@end

@class Ocr;

SWIFT_CLASS("_TtCC14TrustVisionAPI18TVCardInfoResponse5Image")
@interface Image : NSObject
@property (nonatomic, copy) NSString * _Nullable id;
@property (nonatomic, copy) NSString * _Nullable transformedImageId;
@property (nonatomic, copy) NSArray<Info *> * _Nonnull qr;
@property (nonatomic, copy) NSArray<Ocr *> * _Nonnull ocr;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@class TVPoint;

SWIFT_CLASS("_TtCC14TrustVisionAPI18TVCardInfoResponse3Ocr")
@interface Ocr : NSObject
@property (nonatomic, copy) NSString * _Nullable text;
@property (nonatomic, copy) NSArray<TVPoint *> * _Nonnull boundingBox;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtCC14TrustVisionAPI18TVCardInfoResponse4Info")
@interface Info : NSObject
@property (nonatomic, copy) NSString * _Nullable field;
@property (nonatomic, copy) NSString * _Nullable value;
@property (nonatomic, copy) NSString * _Nullable confidenceVerdict;
@property (nonatomic) float confidenceScore;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC14TrustVisionAPI21TVCardInfoSyncRequest")
@interface TVCardInfoSyncRequest : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC14TrustVisionAPI22TVCardTamperingRequest")
@interface TVCardTamperingRequest : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@class CardType;
@class Settings;

SWIFT_CLASS("_TtC14TrustVisionAPI24TVClientSettingsResponse")
@interface TVClientSettingsResponse : NSObject
@property (nonatomic, copy) NSString * _Nullable country;
@property (nonatomic, copy) NSArray<CardType *> * _Nonnull cardTypes;
@property (nonatomic, strong) Settings * _Nullable settings;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

typedef SWIFT_ENUM(NSInteger, Orientation, open) {
  OrientationHorizontal = 0,
  OrientationVertical = 1,
};

typedef SWIFT_ENUM(NSInteger, FaceTrackingMethod, open) {
  FaceTrackingMethodAllFlow = 0,
  FaceTrackingMethodEachGesture = 1,
};


SWIFT_CLASS("_TtCC14TrustVisionAPI24TVClientSettingsResponse19FaceTrackingSetting")
@interface FaceTrackingSetting : NSObject
@property (nonatomic) BOOL enable;
@property (nonatomic) NSInteger maxWarningTime;
@property (nonatomic) float terminateThreshold;
@property (nonatomic) float warningThrehold;
@property (nonatomic) enum FaceTrackingMethod method;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtCC14TrustVisionAPI24TVClientSettingsResponse22LimitTimeLivenessCheck")
@interface LimitTimeLivenessCheck : NSObject
@property (nonatomic) BOOL enable;
@property (nonatomic) NSInteger livenessCheckTimeoutSecond;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtCC14TrustVisionAPI24TVClientSettingsResponse18TerminiateIfNoFace")
@interface TerminiateIfNoFace : NSObject
@property (nonatomic) BOOL enable;
@property (nonatomic) NSInteger maxInvalidFrames;
@property (nonatomic) NSInteger maxIntervalTimeMs;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtCC14TrustVisionAPI24TVClientSettingsResponse11RecordVideo")
@interface RecordVideo : NSObject
@property (nonatomic) BOOL enable;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtCC14TrustVisionAPI24TVClientSettingsResponse17SaveEncodedFrames")
@interface SaveEncodedFrames : NSObject
@property (nonatomic) BOOL enable;
@property (nonatomic) NSInteger framesIntervalMs;
@property (nonatomic) NSInteger framesBatchLen;
@property (nonatomic) BOOL enableLogging;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtCC14TrustVisionAPI24TVClientSettingsResponse21ActiveLivenessSetting")
@interface ActiveLivenessSetting : NSObject
@property (nonatomic, strong) FaceTrackingSetting * _Nullable faceTrackingSetting;
@property (nonatomic, strong) LimitTimeLivenessCheck * _Nullable limitTimeLivenessCheck;
@property (nonatomic, strong) RecordVideo * _Nullable recordVideo;
@property (nonatomic, strong) SaveEncodedFrames * _Nullable saveEncodedFrames;
@property (nonatomic, strong) TerminiateIfNoFace * _Nullable terminateIfNoFace;
@property (nonatomic) NSInteger flowIntervalTimeMs;
@property (nonatomic) BOOL showGestureArrow;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtCC14TrustVisionAPI24TVClientSettingsResponse11IdDetection")
@interface IdDetection : NSObject
@property (nonatomic) BOOL enable;
@end


SWIFT_CLASS("_TtCC14TrustVisionAPI24TVClientSettingsResponse11IdBlurCheck")
@interface IdBlurCheck : NSObject
@property (nonatomic) BOOL enable;
@property (nonatomic) double threshold;
@end


SWIFT_CLASS("_TtCC14TrustVisionAPI24TVClientSettingsResponse12IdGlareCheck")
@interface IdGlareCheck : NSObject
@property (nonatomic) BOOL enable;
@property (nonatomic) double threshold;
@end


SWIFT_CLASS("_TtCC14TrustVisionAPI24TVClientSettingsResponse13IdAutoCapture")
@interface IdAutoCapture : NSObject
@property (nonatomic) BOOL enable;
@property (nonatomic) BOOL showCaptureButton;
@property (nonatomic) NSInteger waitForBestImageTimeMs;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtCC14TrustVisionAPI24TVClientSettingsResponse12IdQrSettings")
@interface IdQrSettings : NSObject
@property (nonatomic) BOOL enable;
@property (nonatomic) NSInteger limitTimeSecond;
@end


SWIFT_CLASS("_TtCC14TrustVisionAPI24TVClientSettingsResponse18IdDetectionSetting")
@interface IdDetectionSetting : NSObject
@property (nonatomic, strong) IdDetection * _Nullable idDetection;
@property (nonatomic, strong) IdBlurCheck * _Nullable blurCheck;
@property (nonatomic, strong) IdGlareCheck * _Nullable glareCheck;
@property (nonatomic, strong) IdAutoCapture * _Nullable idAutoCapture;
@property (nonatomic) BOOL disableCaptureButtonIfAlert;
@property (nonatomic, strong) SaveEncodedFrames * _Nullable saveFrameSetting;
@property (nonatomic, strong) LimitTimeLivenessCheck * _Nullable limitTimeSetting;
@property (nonatomic) NSInteger flowIntervalTimeMs;
@property (nonatomic, strong) IdQrSettings * _Nullable qrSettings;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtCC14TrustVisionAPI24TVClientSettingsResponse21LivenessVerticalCheck")
@interface LivenessVerticalCheck : NSObject
@property (nonatomic) BOOL enable;
@property (nonatomic) NSInteger thresholdInDegree;
@end


SWIFT_CLASS("_TtCC14TrustVisionAPI24TVClientSettingsResponse15LivenessSetting")
@interface LivenessSetting : NSObject
@property (nonatomic, strong) LivenessVerticalCheck * _Nonnull verticalCheck;
@end


SWIFT_CLASS("_TtCC14TrustVisionAPI24TVClientSettingsResponse16ServerLogSetting")
@interface ServerLogSetting : NSObject
@property (nonatomic) BOOL enable;
@end


SWIFT_CLASS("_TtCC14TrustVisionAPI24TVClientSettingsResponse11SdkSettings")
@interface SdkSettings : NSObject
@property (nonatomic, strong) ServerLogSetting * _Nullable serverLogSetting;
@property (nonatomic, strong) ActiveLivenessSetting * _Nullable activeLivenessSetting;
@property (nonatomic, strong) IdDetectionSetting * _Nullable idDetectionSetting;
@property (nonatomic, strong) LivenessSetting * _Nullable livenessSetting;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

enum TVScanQrMode : NSInteger;

SWIFT_CLASS("_TtCC14TrustVisionAPI24TVClientSettingsResponse8Settings")
@interface Settings : NSObject
@property (nonatomic) enum TVScanQrMode scanQrMode;
@property (nonatomic, copy) NSArray<NSString *> * _Nonnull cameraOptions;
@property (nonatomic, copy) NSArray<NSString *> * _Nonnull livenessOptions;
@property (nonatomic) BOOL enableMultipleFaces;
@property (nonatomic) BOOL enableVerifyPortraitSanity;
@property (nonatomic) BOOL enableVerifyIdSanity;
@property (nonatomic) BOOL supportTransaction;
@property (nonatomic) BOOL enableDetectIdCardTampering;
@property (nonatomic, strong) SdkSettings * _Nullable sdkSettings;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@class TVQR;

SWIFT_CLASS("_TtCC14TrustVisionAPI24TVClientSettingsResponse8CardType")
@interface CardType : NSObject
@property (nonatomic, copy) NSString * _Nullable code;
@property (nonatomic, copy) NSString * _Nullable name;
@property (nonatomic) enum Orientation orientation;
@property (nonatomic) BOOL hasBackSide;
@property (nonatomic, strong) TVQR * _Nullable frontQr;
@property (nonatomic, strong) TVQR * _Nullable backQr;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@class FaceImage;
@class CompareFace;

SWIFT_CLASS("_TtC14TrustVisionAPI22TVCompareFacesResponse")
@interface TVCompareFacesResponse : TVBasePolling
@property (nonatomic, strong) FaceImage * _Nullable image1;
@property (nonatomic, strong) FaceImage * _Nullable image2;
@property (nonatomic, copy) NSArray<CompareFace *> * _Nonnull compareFaces;
@end

enum TVCompareFaceResult : NSInteger;

SWIFT_CLASS("_TtCC14TrustVisionAPI22TVCompareFacesResponse11CompareFace")
@interface CompareFace : NSObject
@property (nonatomic) float confidence;
@property (nonatomic) enum TVCompareFaceResult result;
@property (nonatomic, copy) NSString * _Nullable face1Id;
@property (nonatomic, copy) NSString * _Nullable face2Id;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

typedef SWIFT_ENUM(NSInteger, TVCompareFaceResult, open) {
  TVCompareFaceResultMatched = 0,
  TVCompareFaceResultUnmatched = 1,
  TVCompareFaceResultUnsure = 2,
};

@class Face;

SWIFT_CLASS("_TtCC14TrustVisionAPI22TVCompareFacesResponse9FaceImage")
@interface FaceImage : NSObject
@property (nonatomic, copy) NSString * _Nullable id;
@property (nonatomic, copy) NSString * _Nullable transformed_image_id;
@property (nonatomic, copy) NSArray<Face *> * _Nonnull faces;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@class BoundingBox;

SWIFT_CLASS("_TtCC14TrustVisionAPI22TVCompareFacesResponse4Face")
@interface Face : NSObject
@property (nonatomic, copy) NSString * _Nullable id;
@property (nonatomic, strong) BoundingBox * _Nullable boundingBox;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtCC14TrustVisionAPI22TVCompareFacesResponse11BoundingBox")
@interface BoundingBox : NSObject
@property (nonatomic) NSInteger top;
@property (nonatomic) NSInteger right;
@property (nonatomic) NSInteger bottom;
@property (nonatomic) NSInteger left;
@property (nonatomic) NSInteger angle;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@class TVIdCardTampering;

SWIFT_CLASS("_TtC14TrustVisionAPI31TVDetectIdCardTamperingResponse")
@interface TVDetectIdCardTamperingResponse : TVBasePolling
@property (nonatomic, strong) TVIdCardTampering * _Nullable cardTampering;
@property (nonatomic, copy) NSString * _Nullable imageId;
@property (nonatomic, copy) NSString * _Nullable image2Id;
@end

enum TVQRType : NSInteger;

SWIFT_CLASS("_TtC14TrustVisionAPI12TVEnumParser")
@interface TVEnumParser : NSObject
+ (enum TVScanQrMode)TVScanQrModeWithStringValue:(NSString * _Nonnull)stringValue SWIFT_WARN_UNUSED_RESULT;
+ (enum TVQRType)TVQRTypeWithStringValue:(NSString * _Nonnull)stringValue SWIFT_WARN_UNUSED_RESULT;
+ (enum Orientation)OrientationWithStringValue:(NSString * _Nonnull)stringValue SWIFT_WARN_UNUSED_RESULT;
+ (enum TVCompareFaceResult)TVCompareFaceResultWithStringValue:(NSString * _Nonnull)stringValue SWIFT_WARN_UNUSED_RESULT;
+ (enum FaceTrackingMethod)TVFaceTrackingMethodWithStringValue:(NSString * _Nonnull)stringValue SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC14TrustVisionAPI23TVIDCardTamperingDetail")
@interface TVIDCardTamperingDetail : NSObject
@property (nonatomic, copy) NSString * _Nullable name;
@property (nonatomic) float score;
@property (nonatomic, copy) NSString * _Nullable verdict;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC14TrustVisionAPI17TVIdCardTampering")
@interface TVIdCardTampering : NSObject
@property (nonatomic, copy) NSString * _Nullable verdict;
@property (nonatomic) float score;
@property (nonatomic, copy) NSArray<TVIDCardTamperingDetail *> * _Nullable details;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class CardBox;

SWIFT_CLASS("_TtC14TrustVisionAPI15TVImageResponse")
@interface TVImageResponse : NSObject
@property (nonatomic, copy) NSString * _Nonnull id;
@property (nonatomic, copy) NSString * _Nullable transformedImageId;
@property (nonatomic, strong) CardBox * _Nullable cardBox;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtCC14TrustVisionAPI15TVImageResponse7CardBox")
@interface CardBox : NSObject
@property (nonatomic, strong) TVPoint * _Nonnull topLeft;
@property (nonatomic, strong) TVPoint * _Nonnull topRight;
@property (nonatomic, strong) TVPoint * _Nonnull bottomLeft;
@property (nonatomic, strong) TVPoint * _Nonnull bottomRight;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC14TrustVisionAPI12TVLogRequest")
@interface TVLogRequest : NSObject
- (NSDictionary<NSString *, id> * _Nullable)toJsonDict SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC14TrustVisionAPI7TVPoint")
@interface TVPoint : NSObject
@property (nonatomic) NSInteger x;
@property (nonatomic) NSInteger y;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) TVPoint * _Nonnull zero;)
+ (TVPoint * _Nonnull)zero SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

typedef SWIFT_ENUM(NSInteger, TVPollingResult, open) {
  TVPollingResultProcessing = 0,
  TVPollingResultSuccess = 1,
  TVPollingResultFailure = 2,
};


SWIFT_CLASS("_TtC14TrustVisionAPI4TVQR")
@interface TVQR : NSObject
@property (nonatomic) BOOL exist;
@property (nonatomic) enum TVQRType type;
@property (nonatomic) float widthHeightRatio;
- (nonnull instancetype)initWithExist:(BOOL)exist type:(enum TVQRType)type widthHeightRatio:(float)widthHeightRatio OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

typedef SWIFT_ENUM(NSInteger, TVQRType, open) {
  TVQRTypeQrCode = 0,
  TVQRTypeBarCode = 1,
};


SWIFT_CLASS("_TtC14TrustVisionAPI21TVRequestGestureImage")
@interface TVRequestGestureImage : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

typedef SWIFT_ENUM(NSInteger, RequestGestureType, open) {
  RequestGestureTypeUp = 0,
  RequestGestureTypeDown = 1,
  RequestGestureTypeLeft = 2,
  RequestGestureTypeRight = 3,
  RequestGestureTypeFrontal = 4,
};


SWIFT_CLASS("_TtC14TrustVisionAPI14TVRequestImage")
@interface TVRequestImage : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC14TrustVisionAPI14TVRequestVideo")
@interface TVRequestVideo : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC14TrustVisionAPI19TVRequestVideoFrame")
@interface TVRequestVideoFrame : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC14TrustVisionAPI8TVSanity")
@interface TVSanity : NSObject
@property (nonatomic, copy) NSString * _Nullable verdict;
@property (nonatomic) float score;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

typedef SWIFT_ENUM(NSInteger, TVScanQrMode, open) {
  TVScanQrModeNone = 0,
  TVScanQrModeSeparateStep = 1,
  TVScanQrModeWithCard = 2,
};


SWIFT_CLASS("_TtC14TrustVisionAPI21TVTransactionResponse")
@interface TVTransactionResponse : NSObject
@property (nonatomic, copy) NSString * _Nullable id;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC14TrustVisionAPI28TVVerifyIdCardSanityResponse")
@interface TVVerifyIdCardSanityResponse : TVBasePolling
@property (nonatomic, strong) TVImageResponse * _Nullable image1;
@property (nonatomic, strong) TVImageResponse * _Nullable image2;
@property (nonatomic, strong) TVSanity * _Nullable cardSanity;
@end


SWIFT_CLASS("_TtC14TrustVisionAPI24TVVerifyLivenessResponse")
@interface TVVerifyLivenessResponse : TVBasePolling
@property (nonatomic) BOOL isLive;
@property (nonatomic) float score;
@end


SWIFT_CLASS("_TtC14TrustVisionAPI30TVVerifyPortraitSanityResponse")
@interface TVVerifyPortraitSanityResponse : TVBasePolling
@property (nonatomic, strong) TVSanity * _Nullable portraitSanity;
@end

#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#pragma clang diagnostic pop

#endif
